title: Show Hacker
description: "Broadway Lottery & Rush tickets for the thrifty theater lover"
keywords: theater, broadway, tickets, discount, rush, lottery, opensource, hack, lifehacker, hamilton
twitter: showhacker
github: melvitax/showhacker.com
socialimage: https://showhacker.com/images/socialimage.jpg
socialinfo: "Broadway Lottery & Rush tickets for the thrifty theater lover"
socialinfo_callout: "Get Lottery & Rush Tickets"
author:
  name: Melvin Rivera
  twitter: melvitax
  role: designer/developer
markdown: kramdown
url: https://showhacker.com
exclude: ["Gemfile", "Gemfile.lock", "README.md"]
timezone: 'America/New_York'
fonts:
  - "Lato:400,900,700,500,300,100:latin"
sass:
    style: compressed
    sass_dir: assets/css
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"  
  -
    scope:
      path: "broadway"
      type: "pages"
    values:
      layout: "show"
      region: broadway
      permalink: /:path/:basename/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
