title: Show Hacker
description: Broadway lottery and rush ticket agregator
keywords: theater, broadway, tickets, discount, rush, lottery, opensource, hack, lifehacker, hamilton
twitter: showhacker
github: melvitax/showhacker.com
socialimage: http://showhacker.com/images/socialimage.jpg
socialinfo: "Up to date Broadway lottery and rush ticket information"
author:
  name: Melvin Rivera
  twitter: melvitax
  role: designer/developer
thanks:
  -
    name: Ian Rose
    url: https://github.com/ianrose
markdown: kramdown
url: https://showhacker.com
exclude: ["node_modules",  "package.json", "Gemfile", "Gemfile.lock", "README.md", "LICENSE"]
timezone: 'America/New_York'
fonts:
  - "Lato:400,900,700,500,300,100:latin"
sass:
    style: compressed
    sass_dir: styles
collections:
  broadway:
    output: true
    permalink: /broadway/:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "broadway" 
    values:
      layout: "show"
      collection_title: Broadway
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
