title: show.hacker
description: An open source guide to low price theater tickets
keywords: theater, broadway, tickets, discount, rush, lottery, opensource, hack, lifehacker, hamilton
twitter: showhacker
github: melvitax/showhacker.com
socialimage: http://showhacker.com/assets/socialimage.jpg
author:
  name: Melvin Rivera
  twitter: melvitax
  role: designer/developer
thanks:
  -
    name: Ian Rose
    url: https://github.com/ianrose
markdown: kramdown
url: http://showhacker.com
exclude: ["node_modules", "bower_components", "package.json", "bower.json", "Gemfile", "Gemfile.lock", "README.md", "LICENSE"]
timezone: 'America/New_York'
googleanalytics: 'UA-3488813-17'
fonts:
  - "Lato:400,900,700,500,300,100:latin"
sass:
    style: compressed
    sass_dir: styles
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
